version: "3.9"

services:
  php:
    build:
      context: .
    volumes:
      - "./:/var/www/html"
    networks:
      - lumen

  web:
    image: nginx
    container_name: nginx
    working_dir: "/var/www/html"
    volumes:
      - "./:/var/www/html"
      - ".docker/nginx/nginx_template_local.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    networks:
      lumen:
        aliases:
          - myapp.local

  db:
    image: mysql:8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - "mysqldata:/var/lib/mysql"
    networks:
      - lumen

  rediss:
    image: redis:alpine
    volumes:
      - "redisdata:/data"
    ports:
      - "8002:6379"
    networks:
      - lumen

networks:
  lumen:
    driver: bridge

volumes:
  mysqldata:
    driver: local
  redisdata:
    driver: local
